<template>
  <div class="wrapper">
    <next-steps-modal v-if="showNextSteps" @close="showNextSteps = false" />
    <form-wizard title="" subtitle="" class="invoice" color="#538C46" @on-complete="onComplete">
      <tab-content title="Distribution Details" icon="fa fa-cloud-download" :before-change="submitReturnAddress">
        <div class="invoice-box">
          <invoice-header :title="'Distribution Details'" />
          <distribution-details
            :ethereumReturnAddress="ethereumReturnAddress"
            :ethereumWalletProvider="ethereumWalletProvider"
            ref="distributionDetails" />
        </div>
      </tab-content>
      <tab-content title="Payment Details" icon="fa fa-file-text-o" :before-change="submitOrder">
        <div class="invoice-box">
          <invoice-header :title="'Payment Details'" />
          <payment-details
            :usdAmount="usdAmount"
            :coin="coin"
            ref="paymentDetails" />
        </div>
      </tab-content>
      <tab-content title="Invoice Summary" icon="fa fa-qrcode">
        <div class="invoice-box">
          <invoice-summary-header />
          <invoice-summary />
        </div>
      </tab-content>
    </form-wizard>
    <div>
      <div class="footer">This is a unique & encrypt invoice generated by CommerceBlock</div>
      <div class="footer-link">
        <a href="https://www.commerceblock.com/">https://www.commerceblock.com/</a>
      </div>
    </div>
  </div>
</template>

<script>
import gql from 'graphql-tag'
import InvoiceHeader from './InvoiceHeader.vue'
import DistributionDetails from './DistributionDetails.vue'
import PaymentDetails from './PaymentDetails.vue'
import InvoiceSummary from './InvoiceSummary.vue'
import InvoiceSummaryHeader from './InvoiceSummaryHeader.vue'
import NextStepsModal from './NextStepsModal.vue'
import {
  FormWizard,
  TabContent
} from 'vue-form-wizard'

export default {
  name: 'Home',
  components: {
    InvoiceHeader,
    DistributionDetails,
    PaymentDetails,
    InvoiceSummary,
    InvoiceSummaryHeader,
    NextStepsModal,
    FormWizard,
    TabContent
  },
  data () {
    return {
      showNextSteps: false
    }
  },
  computed: {
    apolloClient () {
      return this.$apollo.provider.defaultClient;
    },
    ethereumReturnAddress () {
      return this.returnAddress && this.returnAddress.ethereumReturnAddress;
    },
    ethereumWalletProvider () {
      return this.returnAddress && this.returnAddress.ethereumWalletProvider;
    },
    usdAmount () {
      return this.order && this.order.usdAmount;
    },
    coin () {
      return this.order && this.order.coin;
    }
  },
  methods: {
    onComplete() {
      this.showNextSteps = true;
    },
    submitReturnAddress() {
      if (this.ethereumReturnAddress) {
        // already submitted
        return true;
      }
      const distributionDetails = this.$refs.distributionDetails;
      return this.apolloClient
        .mutate({
          mutation: gql`mutation {
                  createReturnAddress(returnAddress: {
                    ethereumReturnAddress: "${distributionDetails.ethereumReturnAddressInput}"
                    ethereumWalletProvider: "${distributionDetails.ethereumWalletProviderInput}"
                  }) {
                    ethereumReturnAddress
                    ethereumWalletProvider
                  }
                }`})
        .then(result => {
          return Promise.resolve(true);
        }).catch(err => {
          // TODO: show error
          console.log(err)
          return Promise.reject(err);
        });
    },
    submitOrder() {
      if (this.usdAmount) {
        // already submitted
        return true;
      }
      const paymentDetails = this.$refs.paymentDetails;
      return this.apolloClient
        .mutate({
          mutation: gql`mutation {
                  createOrder(order: {
                    usdAmount: "${paymentDetails.usdAmountInput}"
                    coin: "${paymentDetails.coinInput}"
                  }) {
                    usdAmount
                    coin
                    paymentAddress
                    status
                    numnberOfConfirmations
                  }
                }`})
        .then(result => {
          return Promise.resolve(true);
        }).catch(err => {
          // TODO: show error
          console.log(err)
          return Promise.reject(err);
        });
    }
  },
  apollo: {
    returnAddress: {
      query: function () {
        return gql`query {
            returnAddress {
              ethereumReturnAddress
              ethereumWalletProvider
            }
          }`;
      },
      skip() {
        return false;
      },
    },
    order: {
      query: function () {
        return gql`query {
            order {
              usdAmount
              coin
              paymentAddress
              status
              numnberOfConfirmations
            }
          }`;
      },
      skip() {
        return false;
      },
    },
  },
}
</script>

<style scoped>
.wrapper {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

.invoice {
  width: 600px;
  margin: 5px;
}

.invoice-box {
  border-radius: 3px;
  background-color: #FFFFFF;
  box-shadow: 0 2px 7px 0 rgba(0, 0, 0, 0.25);
}

.footer {
  color: #141414;
  font-family: "Open Sans";
  font-size: 16px;
  line-height: 22px;
  text-align: center;
}

.footer-link {
  font-family: "Open Sans";
  font-size: 14px;
  line-height: 19px;
  text-align: center;
}

a:link,
a:visited,
a:hover,
a:active {
  color: rgba(20, 20, 20, 0.5);
}
</style>
