/* eslint-disable global-require */

const fs = require('fs');
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const utils = require('./utils');

module.exports = require('./webpack.base')({
  // Add hot reloading in development
  entry: [
    'webpack-hot-middleware/client',
    path.join(process.cwd(), 'frontend/src/main.js'),
  ],

  // Don't use hashes in dev mode for better performance
  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js',
  },

  // Add development plugins
  plugins: [
    new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
    new webpack.NoEmitOnErrorsPlugin(),
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      templateContent: utils.templateContent(), // eslint-disable-line no-use-before-define
    }),
  ],

  // Load the CSS in a style tag in development
  cssLoaders: [
    { loader: 'style-loader' },
    {
      loader: 'css-loader',
      options: {
        localIdentName: '[path][local]',
        modules: true,
        importLoaders: true,
        sourceMap: true,
      },
    },
    { loader: 'postcss-loader' },
  ],

  // Emit a source map for easier debugging
  devtool: 'cheap-module-eval-source-map',
});
